# Generated by Django 6.1 on 2026-08-25 18:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(db_index=True, error_messages={'unique': 'Ce login est déjà utilisé.'}, help_text='Identifiant unique de connexion (RG-02).', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Le login ne peut contenir que lettres, chiffres et @/./+/-/_ .', regex='^[\\w.@+-]+$')], verbose_name='login')),
                ('prenom', models.CharField(max_length=150, verbose_name='prénom')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='adresse e-mail')),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('directeur', 'Direction'), ('secretaire', 'Secrétaire'), ('caissier', 'Caissier')], default='secretaire', max_length=20, verbose_name='rôle')),
                ('actif', models.BooleanField(default=True, help_text='Désactivé = compte bloqué sans suppression physique (RG-08 historique).', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'verbose_name': 'administrateur',
                'verbose_name_plural': 'administrateurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Caissier',
            fields=[
            ],
            options={
                'verbose_name': 'caissier',
                'verbose_name_plural': 'caissiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
            ],
            options={
                'verbose_name': 'directeur',
                'verbose_name_plural': 'directeurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
            ],
            options={
                'verbose_name': 'secrétaire',
                'verbose_name_plural': 'secrétaires',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
