# Generated by Django 6.1 on 2026-08-26 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actif',
            field=models.BooleanField(default=True, help_text='Désactivé = compte bloqué sans suppression physique.', verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(db_index=True, error_messages={'unique': 'Ce login est déjà utilisé.'}, help_text='Identifiant unique de connexion.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Le login ne peut contenir que lettres, chiffres et @/./+/-/_ .', regex='^[\\w.@+-]+$')], verbose_name='login'),
        ),
    ]
