# Generated by Django 6.1 on 2026-08-25 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, help_text='Unique, ex: MER-2024-001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Matricule: lettres majuscules, chiffres et tirets uniquement.', regex='^[A-Z0-9\\-]+$')], verbose_name='matricule')),
                ('nom', models.CharField(db_index=True, max_length=100, verbose_name='nom')),
                ('post_nom', models.CharField(blank=True, max_length=100, verbose_name='post-nom')),
                ('prenom', models.CharField(db_index=True, max_length=100, verbose_name='prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('tuteur_nom', models.CharField(max_length=150, verbose_name='nom du tuteur')),
                ('tuteur_lien', models.CharField(choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Autre', 'Autre')], default='Père', max_length=20, verbose_name='lien de parenté')),
                ('tuteur_telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone du tuteur')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='classes.anneescolaire', verbose_name='année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='classes.classe', verbose_name='classe')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['nom', 'post_nom', 'prenom'],
                'indexes': [models.Index(fields=['matricule'], name='students_el_matricu_93aef8_idx'), models.Index(fields=['nom', 'prenom'], name='students_el_nom_1ee163_idx'), models.Index(fields=['classe'], name='students_el_classe__d48a76_idx')],
            },
        ),
    ]
