# Generated by Django 6.1 on 2026-08-26 00:21

import apps.students.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='annee_scolaire',
            field=models.CharField(db_index=True, default=apps.students.models.get_annee_scolaire_courante, help_text='Gérée automatiquement', max_length=9, verbose_name='année scolaire'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Généré automatiquement, ex: MER-2025-001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Matricule: lettres majuscules, chiffres et tirets uniquement.', regex='^[A-Z0-9\\-]+$')], verbose_name='matricule'),
        ),
    ]
