# Generated by Django 5.1.8 on 2026-09-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_eleve_annee_scolaire_alter_eleve_matricule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['-date_inscription', '-id'], 'verbose_name': 'élève', 'verbose_name_plural': 'élèves'},
        ),
    ]
