# Generated by Django 6.1 on 2026-08-26 14:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0002_alter_eleve_annee_scolaire_alter_eleve_matricule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(db_index=True, max_length=9, verbose_name='année scolaire')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Le montant doit être strictement positif.')], verbose_name='montant payé')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='date de paiement')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='mode de paiement')),
                ('montant_total_du', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total dû')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='solde')),
                ('arrieres', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='arriérés')),
                ('observation', models.TextField(blank=True, verbose_name='observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='agent')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='students.eleve', verbose_name='élève')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='fees.typefrais', verbose_name='type de frais')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="date d'émission")),
                ('statut', models.CharField(choices=[('genere', 'Généré'), ('imprime', 'Imprimé'), ('annule', 'Annulé')], default='genere', max_length=10, verbose_name='statut')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus_emmis', to=settings.AUTH_USER_MODEL, verbose_name='agent émetteur')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus', to='students.eleve', verbose_name='élève')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recu_associe', to='payments.paiement', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'reçu',
                'verbose_name_plural': 'reçus',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='payments_pa_eleve_i_95c71f_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='payments_pa_date_pa_ca080a_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['agent'], name='payments_pa_agent_i_694861_idx'),
        ),
    ]
