# Generated by Django 6.1 on 2026-08-25 23:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'type de frais',
                'verbose_name_plural': 'types de frais',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Le montant doit être strictement positif.')], verbose_name='montant')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date de création')),
                ('classes', models.ManyToManyField(blank=True, related_name='frais', to='classes.classe', verbose_name='classes')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_set', to='fees.typefrais', verbose_name='type de frais')),
            ],
            options={
                'verbose_name': 'frais',
                'verbose_name_plural': 'frais',
                'ordering': ['type_frais__libelle', '-date_creation'],
            },
        ),
    ]
