# Generated by Django 6.1 on 2026-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frais',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], db_index=True, default='CDF', max_length=3, verbose_name='devise'),
        ),
    ]
