# Generated by Django 6.1 on 2026-08-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_index=True, help_text='Ex: 2024-2025', max_length=20, unique=True, verbose_name='libellé')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, help_text='Ex: 1ère A', max_length=20, unique=True, verbose_name='nom')),
                ('niveau', models.IntegerField(choices=[(1, '1ère Primaire'), (2, '2ème Primaire'), (3, '3ème Primaire'), (4, '4ème Primaire'), (5, '5ème Primaire'), (6, '6ème Primaire')], db_index=True, verbose_name='niveau')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2, verbose_name='section')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['niveau', 'section', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('niveau', 'section'), name='unique_niveau_section')],
            },
        ),
    ]
