# Generated by Django 6.1 on 2026-08-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0002_alter_eleve_annee_scolaire_alter_eleve_matricule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnneeScolaire',
        ),
    ]
