# Generated by Django 5.1.15 on 2026-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_delete_anneescolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.IntegerField(choices=[(1, '1ère'), (2, '2ème'), (3, '3ème'), (4, '4ème'), (5, '5ème'), (6, '6ème')], db_index=True, verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Généré automatiquement : niveau + section', max_length=20, unique=True, verbose_name='nom'),
        ),
    ]
