# Generated by Django 5.1.15 on 2026-08-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classe_niveau_alter_classe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2, verbose_name='section'),
        ),
    ]
